spring:
  application:
    name: ycc
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
server:
  port: 8899

mybatis-plus:
  mapper-locations:
    - classpath:mapper/*.xml